src/Entity/Prestation.php
<?php

namespace App\Entity;

use App\Repository\PrestationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PrestationRepository::class)
 */
class Prestation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantite;

    /**
     * @ORM\Column(type="float")
     */
    private $ttc;

    /**
     * @ORM\ManyToOne(targetEntity=Devis::class, inversedBy="prestation",cascade={"persist"})
     */
    private $devis;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getTtc(): ?float
    {
        return $this->ttc;
    }

    public function setTtc(float $ttc): self
    {
        $this->ttc = $ttc;

        return $this;
    }

    public function getDevis(): ?Devis
    {
        return $this->devis;
    }

    public function setDevis(?Devis $devis): self
    {
        $this->devis = $devis;

        return $this;
    }

    public function getTotalTTC()
    {

        return $this->getTtc() * $this->getQuantite();
    }

    public function getHT($tva)
    {
        return $this->getTtc() * (1 - intval($tva) / 100);
    }

    public function getTotalHT($tva)
    {
        return $this->getTotalTTC() * (1 - intval($tva) / 100);
    }
    public function __toString()
    {
        return $this->description;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function isComposant()
    {
        if ($this->type == 'composant')
            return true;
        return false;
    }

    public function getPrix()
    {
        return $this->ttc;
    }
}

src/Controller/CatalogueController.php
<?php

namespace App\Controller;

use App\Entity\Pc;
use App\Entity\Revendeur;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CatalogueController extends AbstractController
{
    #[Route('/catalogue', name: 'catalogue')]
    public function index(): Response
    {
        $user = $this->getUser()->getId();
        $revendeur = $this->getDoctrine()->getRepository(Revendeur::class)->findOneBy(['user' => $user]);



        return $this->render('catalogue/index.html.twig', [
            'controller_name' => 'CatalogueController',
            'revendeur' => $revendeur,
        ]);
    }
}

templates/catalogue/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CatalogueController!
{% endblock %}

{% block javascripts %}
	<script src="/js/catalogue.js"></script>
{% endblock %}

{% block body %}
	{% if revendeur.offre is not empty %}
		<div class="container">
			<h5>Offres Spéciales :</h5>
			<p class="text-danger ms-4 fs-5">
				{{revendeur.offre}}
			</p>
		</div>

	{% endif %}

	<div class=" d-flex justify-content-around flex-wrap">
		{% for pcRevendeur in revendeur.getPcRevendeurs() %}

			{% set item = pcRevendeur.pc %}
			<div class="d-flex flex-column align-items-center shadow rounded m-5 px-3 pt-3">
				<div class="d-flex">
					<ul class="d-flex flex-column">
						{% for img in item.getImages() %}
							<li class=" mb-3 {% if loop.index == 1 %} active {% endif %}">
								<img src="https://www.backoffice.micro76.fr/img/pc/{{img}}" alt="pc" width="50" onmouseover="changePicture('{{item.sku}}')">
							</li>


						{% endfor %}
					</ul>
					<div class="ms-2">
						<img src="https://www.backoffice.micro76.fr/img/pc/{{item.getDisplayImg()}}" alt="pc" width="250" id="{{item.sku}}">

					</div>


				</div>
				<div class="w-100">
					<h4>{{item}}</h4>
					<div class="d-flex  justify-content-around align-items-center">

						<span class="fs-5">{{pcRevendeur.prix}}
							€</span>
						<button class="btn btn-info">Ajouter au panier</button>
					</div>
				</div>
				{% if item.delai is not empty %}
					<i class="text-start w-100 mt-3">Expédition sous
						{{item.delai}}</i>

				{% endif %}

			</div>
		{% endfor %}

	</div>
{% endblock %}